version: "3.3"
services:
    mongo:
        image: mongo
        ports:
            - "5004:5004"
        command: mongod --port 5004
        container_name: blogging-app-mongodb
        environment:
            - ./.env
        volumes:
            - mongo-data:/data/db
volumes:
    mongo-data:
