version: "3"
services:
    mongo:
        image: mongo:latest
        container_name: mongo
        env_file:
            - ./.env.local
        volumes:
            - mongo:/data/db
        ports:
            - "27018:27017"
    postgres:
        image: postgres
        env_file:
            - ./.env.local
        ports:
            - '30001:30001'
        volumes:
            - postgres:/var/lib/postgresql/data
        command: -p 30001
volumes:
    mongo:
    postgres:
        driver: local
